# Generated by Django 4.1.7 on 2023-02-28 00:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_profile_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("caption", models.TextField()),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("num_of_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
