# Generated by Django 4.1.7 on 2023-03-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
